apiVersion: v1
kind: Secret
metadata:
  name: bot-secrets
  namespace: bot
type: Opaque
data: # Fill up with your secrets, use the base64 encoding: echo -n 'YOUR_STRING' | base64
  # Required secrets, please make sure to fill them up.
  DISCORD_TOKEN: '' # Your Discord bot token
  DISCORD_CLIENT_ID: '' # Your Discord client ID
  MONGODB_CONNECTION: '' # Your MongoDB connection string, mongodb://hans:S3cret@localhost:27017 if using docker compose for development.
  MONGODB_DATABASE: '' # Default database to work with, if none specified, `dev` will be used.
  BOT_GUILD_ID: '' # Your Discord Guild ID, the home of your Bot.
  CRYPTO_KEY: '' # Your crypto key, used to encrypt/decrypt data.

  # All bellow are optional, but some commands or functionality won't work.
  WEATHER_API: '' # Grab one at https://openweathermap.org/api

  # Not used currently, but will be used in the future.
  GITHUB_API_TOKEN: '' # Uses to fetch the latest git merge, send the details in a card.
  OPENAI_API_KEY: ''
  OPENAI_ORGANIZATION_ID: ''
